- name: Copy KDE config files
  ansible.builtin.copy:
    src: "{{ config_files_repo_path }}/{{ inventory_hostname }}/kde/{{ item }}"
    dest: "/home/{{ ansible_user }}/.config/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "600"
    remote_src: true
  loop:
    - "kdeglobals"
    - "kglobalshortcutsrc"
    - "khotkeysrc"
    - "klipperrc"
    - "kwinrc"
    - "kwinrulesrc"
