- name: Copy KDE config files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "600"
  loop:
    - src: "kdeglobals"
      dest: "/home/{{ ansible_user }}/.config/kdeglobals"
    - src: "kglobalshortcutsrc"
      dest: "/home/{{ ansible_user }}/.config/kglobalshortcutsrc"
    - src: "khotkeysrc"
      dest: "/home/{{ ansible_user }}/.config/khotkeysrc"
    - src: "klipperrc"
      dest: "/home/{{ ansible_user }}/.config/klipperrc"
    - src: "kwinrc"
      dest: "/home/{{ ansible_user }}/.config/kwinrc"
    - src: "kwinrulesrc"
      dest: "/home/{{ ansible_user }}/.config/kwinrulesrc"
    - src: "konsolerc"
      dest: "/home/{{ ansible_user }}/.config/konsolerc"
    - src: "konsole_profile"
      dest: "/home/{{ ansible_user }}/.local/share/konsole/asdf.profile"
    - src: "gruvbox_konsole"
      dest: "/home/{{ ansible_user }}/.local/share/konsole/Gruvbox_dark.colorscheme"
