- name: Configure themes
  ansible.builtin.import_tasks:
    file: "configure_theme.yaml"

- name: Copy config files
  tags:
    - "kde_config_files"
    - "KDE_config_files"
  ansible.builtin.import_tasks:
    file: "copy_config_files.yaml"
