- name: Remove unneeded packages
  ansible.builtin.dnf:
    name: "{{ manage_packages_dnf_packages_remove }}"
    state: absent
    autoremove: true

- name: Upgrade all packages
  tags:
    - dnf_upgrade
    - dnf_update
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true

- name: Install base packages
  ansible.builtin.dnf:
    name: "{{ manage_packages_dnf_base_packages }}"
    state: present
    update_cache: true
    allowerasing: true

- name: Install vscode packages
  tags:
    - "vscode"
    - "Vscode"
    - "Code"
  ansible.builtin.dnf:
    name: "{{ manage_packages_dnf_vscode_packages }}"
    state: present
    update_cache: true
    allowerasing: true

- name: Install Hashicorp packages
  tags:
    - "hashicorp"
    - "Hashicorp"
  ansible.builtin.dnf:
    name: "{{ manage_packages_dnf_hashicorp_packages }}"
    state: present
    update_cache: true
    allowerasing: true

- name: Install host specific packages
  ansible.builtin.dnf:
    name: "{{ host_packages }}"
    state: present
    update_cache: true
    allowerasing: true
  when: host_packages is defined
