- name: Add flathub repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    method: "user"
    state: present

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ flatpak_packages_install }}"
    remote: flathub
    method: "user"
    state: present
