- name: Set hostname
  ansible.builtin.import_tasks:
    file: "hostname.yaml"

- name: Configure firewall
  ansible.builtin.import_tasks:
    file: "firewall.yaml"

- name: Configure grub
  ansible.builtin.import_tasks:
    file: "configure_grub.yaml"

- name: Configure kernel modules
  tags:
    - "kernel_modules"
    - "configure_kernel_modules"
  ansible.builtin.import_tasks:
    file: "configure_kernel_module.yaml"
