- name: Set homedirectory acl
  ansible.posix.acl:
    path: "/home/{{ ansible_user }}"
    etype: "other"
    permissions: "---"
    default: true
    recursive: true
    state: "present"

- name: Change user shell
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh

- name: Add user to libvirt group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: libvirt
