- name: Ensure ~/bin exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/bin"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "700"

- name: Copy mount script
  ansible.builtin.copy:
    src: "mount-nas-sshfs"
    dest: "/home/{{ ansible_user }}/bin/mount-nas-sshfs"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "700"
